sudo: false
services:
  - docker
language: bash
before_install:
  - eval "$(ssh-agent -s)"
  - openssl aes-256-cbc -K $encrypted_e58dbf8351c6_key -iv $encrypted_e58dbf8351c6_iv -in ${TRAVIS_BUILD_DIR}/travis/environment-operator-deploykey.enc -out ~/.ssh/travis-rsa -d
  - chmod 600 ~/.ssh/travis_rsa
  - ssh-add ~/.ssh/travis_rsa
install:
  - ${TRAVIS_BUILD_DIR}/travis/releaseVersioning.sh
before_script:
  - ${TRAVIS_BUILD_DIR}/travis/unittest.sh
script:
  - ${TRAVIS_BUILD_DIR}/travis/build.sh
after_success:
  - ${TRAVIS_BUILD_DIR}/travis/releaseTagging.sh
#safelist
branches:
  only:
    - dev
    - master
